### ISSUE TITLE
Versioning of SE-MEI

### ISSUE THREAD

**Issue by samfux84** [dpryan79/SE-MEI#2]
Hi,

could you please consider to implement a versioning for your software.

If scientists use your software, they would like to cite it if they use the results in a publication. In order to make results reproducible, people need to use the same version of a software. This is only possible if there is any versioning at all.

**Comment by dpryan79** [comment]
I honestly never expected anyone other than me to find this repository useful, so I never bothered. If you plan on actually using this then sure, I can tag a release.

**Comment by samfux84** [comment]
@dpryan79 Thank you for your feedback.

I got a request from a scientist and just installed your code on the high-performance computing cluster of ETH Zurich, which has more than 2000 users.

Best regards

Sam
