### ISSUE TITLE
extract no soft-clipped region

### ISSUE THREAD

**Issue by cascoamarillo** [dpryan79/SE-MEI#6]
Nice tool. But how would you do to:
-extract the read region that is not sotf-clipped?
-extract the entire (original) read?

Thanks

**Comment by dpryan79** [comment]
The tool isn't designed to do that, the code would have to be changed.

**Comment by cascoamarillo** [comment]
Thanks for the quick reply. Yes, I understand. I'll try to look at the code from extractSoftclipped. I was thinking that along with the extracted clipped read regions (=TEs), what if I would like to look at the different insertion points (=non-clipped read regions) in the genome (preference insertion points?), and if it could be done all together here. Thank you.
